<?php
/**
 * Created by Qoliber
 *
 * @category    Qoliber
 * @package     Qoliber_CaseStudyManager
 * @author      Jakub Winkler <jwinkler@qoliber.com>
 */

/** @var \Qoliber\CaseStudyManager\Block\Customer\CaseStudy\ListCaseStudy $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php $caseStudies = $block->getCaseStudies(); ?>
<?php if ($caseStudies && $caseStudies->getSize()): ?>
    <div class="mt-8 flex flex-col">
        <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
                <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
                    <table class="min-w-full divide-y divide-gray-300">
                        <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold
                                         text-gray-900 sm:pl-6"><?= $escaper->escapeHtml(__('Store Logo')) ?></th>
                                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold
                                         text-gray-900 sm:pl-6"><?= $escaper->escapeHtml(__('Store name')) ?></th>
                                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                                    <?= $escaper->escapeHtml(__('Status')) ?></th>
                                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                                    <span class="sr-only"><?= $escaper->escapeHtml(__('Actions')) ?></span>
                                </th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-gray-200 bg-white">
                            <?php foreach ($caseStudies as $caseStudy): ?>
                                <tr>
                                    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm sm:pl-6">
                                        <?php if ($caseStudy->getImage()): ?>
                                            <img src="<?=
                                                    $escaper->escapeUrl($block->getImageUrl($caseStudy->getImage())) ?>"
                                                 alt="<?=
                                                    $escaper->escapeHtml($caseStudy->getTitle()) ?>"
                                                 class="h-12 w-12 object-cover rounded-lg shadow-sm" />
                                        <?php else: ?>
                                            <?php $image = 'Qoliber_CaseStudyManager/images/placeholder.svg'; ?>
                                            <div class="h-12 w-12 rounded-lg bg-gray-100 flex
                                                        items-center justify-center">
                                                <img src="<?= /** @noEscape */ $block->getViewFileUrl($image); ?>"
                                                     alt="<?= $escaper->escapeHtml(__('Placeholder')) ?>"
                                                     class="h-6 w-6 text-gray-400" />
                                            </div>
                                        <?php endif; ?>
                                    </td>
                                    <td class="whitespace-nowrap py-4 pl-4 pr-3
                                               text-sm font-medium text-gray-900 sm:pl-6">
                                        <?= $escaper->escapeHtml($caseStudy->getTitle()) ?>
                                    </td>
                                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                                        <span class="inline-flex rounded-full px-2 text-xs font-semibold leading-5
                                        <?= $caseStudy->getIsActive()
                                            ? 'bg-green-100 text-green-800'
                                            : 'bg-red-100 text-red-800' ?>">
                                            <?= $caseStudy->getIsActive()
                                                ? /** @noEscape */ __('Active')
                                                : /** @noEscape */ __('Inactive') ?>
                                        </span>
                                    </td>
                                    <td class="relative whitespace-nowrap py-4 pl-3 pr-4
                                               text-right text-sm font-medium sm:pr-6">
                                        <a href="<?= $escaper->escapeUrl($block->getEditUrl($caseStudy->getId())) ?>"
                                           class="text-indigo-600 hover:text-indigo-900">
                                            <?= /** @noEscape */ $escaper->escapeHtml(__('Edit')) ?>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
<?php else: ?>
    <div class="mt-8 rounded-md bg-blue-50 p-4">
        <div class="flex">
            <div class="ml-3">
                <p class="text-sm font-medium text-blue-800">
                    <?= $escaper->escapeHtml(__('You have no case studies yet.')) ?>
                </p>
            </div>
        </div>
    </div>
<?php endif; ?>
